### ISSUE TITLE
Create technical document

### ISSUE THREAD

**Issue by ys112** [CS3219-AY2425S1/cs3219-ay2425s1-project-g20#26]

**Comment by Cloud7050** [comment]
For this, are we proceeding with a (new?) md file in the monorepo? Would be good to reuse as much of the existing md content (from the READMEs) as we can. I will try to update the READMEs as I go.

**Comment by Cloud7050** [comment]
We will be proceeding with md file.

**Comment by Cloud7050** [comment]
Could document us building `@common` in Docker and having the `/dist` entrypoints. It causes deprecation warnings in dev mode, but is needed for interop and for imports to be found.

**Comment by Cloud7050** [comment]
This is due later than the D5/D6 Friday deadline, where we will have initial Zoom demo with mentor.

**Comment by Cloud7050** [comment]
There's still a bit of inconsistency, for example in the naming of the frontend env vars (websocket vs API URLs), as well as in the secret and path names for docker envs.

**Comment by Cloud7050** [comment]
#110 #111 #112 #113
