### ISSUE TITLE
Questions service constants file

### ISSUE THREAD

**Issue by Cloud7050** [CS3219-AY2425S1/cs3219-ay2425s1-project-g20#36]
Currently, the defaults for our env variables are spread across various files.

Let's combine them into a single constants file, and update the docs accordingly.

**Comment by Cloud7050** [comment]
Other constants such as the path to our sample questions JSON file would also be eligible.

**Comment by Cloud7050** [comment]
We could also potentially use constants for the status codes our router responds with. They should already be available out there without having to define them ourselves.

Edit: `pnpm add http-status-codes --filter @services/question-service`

**Comment by bachletuankhai** [comment]
With the existence of `docker-compose.yml`, we can view the env for all services there. Is it good enough?

**Comment by Cloud7050** [comment]
That is nice as a reference, though I think the values there are still (necessarily) duplicates of those we also have elsewhere in the codebase. As an example, last I checked the question service has these sorts of values in multiple files (e.g. index.ts, collection.ts). Then we also put the same values in our example + local env files, and again in the documentation.

We could seek to minimise how spread out they are and the times they are repeated. Perhaps common could export a shared constants + util package.

**Comment by Cloud7050** [comment]
See also #69
