### ISSUE TITLE
Implement backend routes to CRUD questions

### ISSUE THREAD

**Issue by donljh** [CS3219-AY2425S1/cs3219-ay2425s1-project-g20#4]

**Comment by Cloud7050** [comment]
Question, what does this entail? Does the frontend page for #5 contact the backend questions service #3 directly?

**Comment by donljh** [comment]
> Question, what does this entail? Does the frontend page for #5 contact the backend questions service #3 directly?

Yes, the questions service will expose it own set of API endpoints

**Comment by Cloud7050** [comment]
> Yes, the questions service will expose it own set of API endpoints

If #3 provides the API, and #5 consumes the API, then what else does #4 have to do atm?
