### ISSUE TITLE
Split up Database to their own services

### ISSUE THREAD

**Issue by ys112** [CS3219-AY2425S1/cs3219-ay2425s1-project-g20#56]
To separate the database based on the microservice architecture,

**Comment by Cloud7050** [comment]
See also changes in #97

**Comment by Cloud7050** [comment]
Atm the code is ready to use different service accounts (ie separate DBs) for each of the 3 services that use Firestore. If it's not a requirement to also actually have different projects for them all, then we can just reuse the same existing JSON credentials, pasted 3 times.

We'll just need to update the docs, then we can probably close this in that case.

**Comment by Cloud7050** [comment]
Moved docs task into #105
