### ISSUE TITLE
Unit tests for questions service

### ISSUE THREAD

**Issue by donljh** [CS3219-AY2425S1/cs3219-ay2425s1-project-g20#6]
N2H, will rollover to subsequent milestones.

Unit testing is specifically intended for the controller, not e2e.

**Comment by Cloud7050** [comment]
Will await #3 and see how to go about this, open to suggestions for tech.

**Comment by Cloud7050** [comment]
Have researched a few options, seems very hard to properly mock a Firestore collection alongside its snapshots etc. `ts-mock-firebase` is no longer maintained.

There exists Firebase Emulator, but that forces our initially async Jest tests to each be run consecutively, and having to clean up the DB between each test.

There is also spy functionality in Jest, but that's checking on individual Firestore (emulator) calls done by the controller. Ideally I'd just want to start with a stateless DB snapshot that I can reuse in various tests, and compare the new snapshot after each test.

---

I think as a first step, we need another layer of abstraction for the DB. The controller should also not be aware of the implementation details of other layers. e.g. it should not need to interact with req/res from the router directly. It should also not be aware of the very specfic way in which we have to work with our DB of choice (i.e. the admittedly convenient calls we use from the Firestore lib). Both these things are contained in the current controller, making it even harder to design unit tests on the controller logic only.

Looking for any thoughts and suggestions esp. if you have more experience with testing.

**Comment by Cloud7050** [comment]
If we make our model handle the specifics of interacting with Firestore, it then becomes possible to mock it in the context of the controller with in-memory storage.

**Comment by Cloud7050** [comment]
Framework is contained in #38, writing of actual tests deprioritised in favour of #30 for D3.

**Comment by Cloud7050** [comment]
https://github.com/CS3219-AY2425S1/cs3219-ay2425s1-project-g20/pull/38#issuecomment-2395115083

**Comment by Cloud7050** [comment]
Will opt to keep N4 from the project doc instead, as the related N11 for this requires very extensive tests and CI.
