### ISSUE TITLE
 Implement the matching service with message queue

### ISSUE THREAD

**Issue by ys112** [CS3219-AY2425S1/cs3219-ay2425s1-project-g20#63]
Develop the backend logic that uses a message queue to match users based on their selected topic and difficulty level. Integrate with the provided user service (code given for user service).

For submission:
**Debug/log message indicating the status of the queue before and after the match**

**Comment by Cloud7050** [comment]
To clarify, they have not provided us a second batch of new stuff after we've integrated the user service?
